### ISSUE TITLE
It doesn't work properly when Backlog Screenshots are activated

### ISSUE THREAD

**Issue by thiagosalles** [eHonnef/tibia-screenshot-organizer#1]
If we go to `Options > Screenshots` and select the option `Keep Backlog of the Screenshots of the Last 5 seconds`, the files will be generated in a different format:
```
2023-01-27_204304929_Char Name_BestiaryEntryUnlocked_1
```

**Suggestion:**
Instead of getting the values from back to front (`prs[-2]` and `prs[-1]`), get them normally with positive indexes (`prs[2]` and `prs[3]`)

**Comment by eHonnef** [comment]
Good catch, just fixed with 8619fc8b4ca3fd807265fc8c59e99e52b046b73b
